import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import FormBase from "../components/forms/FormBase";
import styles from "../styles/Home.module.css";
import { Formik, Form, Field, ErrorMessage } from "formik";
import AddCategoryForm from "../components/forms/AddCategoryForm";
import AddItemForm from "../components/forms/AddItemForm";
import { addCategories } from "../api/base-api";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Boutique Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AddCategoryForm />
      <h1>--------------------------------------</h1>
      <AddItemForm />
      <h1>--------------------------------------</h1>
      <button onClick={() => addCategories({name:"test",description:"test"})}>Click me</button>

      {/* <Footer/> */}
    </div>
  );
};

export default Home;
